
const DEFAULT_DRAFT_BLOCK_HEIGHT = 50; // ~47px
const LAZY_LOAD_BLOCK_OFFSET = 4;

const MAX_LAZY_LOAD_BLOCKS  = 50;
const MAX_BLOCKS_TO_DISPLAY = MAX_LAZY_LOAD_BLOCKS + (2 * LAZY_LOAD_BLOCK_OFFSET);

module.exports = {
  DEFAULT_DRAFT_BLOCK_HEIGHT,
  LAZY_LOAD_BLOCK_OFFSET,
  MAX_LAZY_LOAD_BLOCKS,
  MAX_BLOCKS_TO_DISPLAY,
};